# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f71cd0e7b81cd698cb2fdfbaa0e5be8d69bce25b56ddb1483c166358eb6f45d85e973b014cd2369fb27c37f0f46a6f5e552407263e327d17e338a4053882b2a

test:
  secret_key_base: 50cda860fc414a02d9dc4a74ea7cbb13ef1ad6828743e584df0d1b62653fe65fcaf33197d985b1ba8e4216fe8a199d158437366cf98db310a8db5253d6b68e0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
